development:
  adapter: mysql2
  encoding: utf8
  database: test_openmeetings_development
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
  
openmeetings_dev:
  adapter: mysql2
  encoding: utf8
  database: openmeetings
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock